import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { chillax } from "./fonts/chillax";
import SmoothScroll from "./components/SmoothScroll";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${chillax.className} antialiased`}>
        <SmoothScroll />
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
