import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { chillax } from "./fonts/chillax";
import SmoothScroll from "./components/SmoothScroll";
import NavbarMobile from "./components/navbarMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${chillax.className} antialiased`}
      >
        <SmoothScroll />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
